AmarSomoy/Models/ViewModel/TaskViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AmarSomoy.Models.ViewModel
{
    public class TaskViewModel
    {
        public int TaskId { get; set; }
        public string TaskDescription { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }

        public TimeSpan TSWorkingHour
        {
            get
            {
                TimeSpan diff = EndTime - StartTime;
                return diff;
            }
            set { }
        }
        public string WorkingHour
        {
            get
            {
                TimeSpan diff = EndTime - StartTime;
                return diff.ToString("h'h 'm'm 's's'");
                //double hours = diff.TotalHours;
                //return hours;
            }
            set { }
        }
        public string ProjectName { get; set; }
        public string ProjectCode { get; set; }

        public Boolean IsSelectedReport { get; set; }
        public string trColor { get; set; }
    }
}

AmarSomoy/Controllers/TaskController.cs
using AmarSomoy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AmarSomoy.Models.ViewModel;
using Telerik.Web.Mvc;
using System.Data.Entity;
using UPASS.EmailSender;
using System.Text;
using AmarSomoy.Infrastructure.Alerts;

namespace AmarSomoy.Controllers
{
    public class TaskController : BaseController
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private int pCode;

        // GET: Project
        public ActionResult Index()
        {
            PrepareViewBag("", "");
            return View();
        }

        // GET: Project/Details/5
        public ActionResult Details(int pId)
        {
            var com = db.Tasks.FirstOrDefault(co => co.TaskId == pCode);
            return View(com);
        }

        // GET: Project/Create
        public ActionResult Create()
        {
            var profile = db.Profiles.FirstOrDefault(p => p.UserId == SessionUtility.SessionContainer.USER_ID);
            PrepareViewBag(profile.CompanyCode, "");
            TaskModel task = new TaskModel();
            task.TaskOwner = profile.FirstName + " " + profile.LastName;
            task.TaskOwnerId = profile.UserId;
            return View(task);
        }

        private void PrepareViewBag(string pCompanyCode, string pProjectCode)
        {
            var CompList = db.Companies.Where(com => com.IsDeleted == false);

            ViewBag.CompanyList = new SelectList(CompList.OrderBy(k => k.CompanyName), "CompanyCode", "CompanyName", pCompanyCode);

            var ProjectList = db.Projects.Where(com => com.IsDeleted == false);

            ViewBag.ProjectList = new SelectList(ProjectList.OrderBy(k => k.ProjectName), "ProjectCode", "ProjectName", pProjectCode);
        }

        // POST: Project/Create
        [HttpPost]
        public ActionResult Create(TaskModel pTask)
        {
            PrepareViewBag(pTask.CompanyCode, pTask.ProjectCode);
            if (ModelState.IsValid)
            {
                if (!ValidateTimeOverlap(false, pTask))
                {
                    try
                    {
                        pTask.IsNew = true;
                        base.SetObjectStatus(pTask);
                        db.Tasks.Add(pTask);
                        db.SaveChanges();
                        return Json(new { STATUS = "Success", MESSAGE = "Data saved successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    catch (Exception ex)
                    {
                        return Json(new { STATUS = "Exception", MESSAGE = ex.Message }, JsonRequestBehavior.AllowGet);
                    }

                }
                else
                {
                    return RedirectToAction<TaskController>(r => r.Create(pTask)).WithSuccess("Time overlapped");
                }
            }
            return View(pTask).WithError("Invalid Model");

        }

        private bool ValidateTimeOverlap(Boolean pIsUpdate, TaskModel pTask)
        {
            Boolean IsOverlap = false;
            if (!pIsUpdate)
            {
                var tasks = (from tDB in db.Tasks
                             where ((tDB.StartTime >= pTask.StartTime && tDB.StartTime != null)
                             && (tDB.StartTime <= pTask.EndTime && tDB.StartTime != null))
                            || ((tDB.EndTime >= pTask.StartTime && tDB.EndTime != null)
                             && (tDB.EndTime <= pTask.EndTime && tDB.EndTime != null))
                             && tDB.TaskOwnerId == pTask.TaskOwnerId && tDB.IsDeleted == false
                             select new TaskViewModel()
                             {
                                 TaskId = tDB.TaskId,
                             }).ToList();
                if (tasks != null && tasks.Count() > 0)
                    IsOverlap = true;

            }
            return IsOverlap;
        }

        // GET: Project/Edit/5
        public ActionResult Edit(int pId)
        {
            var task = db.Tasks.FirstOrDefault(co => co.TaskId == pId);
            PrepareViewBag(task.CompanyCode, task.ProjectCode);
            var profile = db.Profiles.FirstOrDefault(p => p.UserId == SessionUtility.SessionContainer.USER_ID);
            task.TaskOwner = profile.FirstName + " " + profile.LastName;
            task.TaskOwnerId = profile.UserId;
            return View(task);
        }

        // POST: Company/Edit/5
        [HttpPost]
        public ActionResult Edit(int pId, TaskModel pTask)
        {
            try
            {
                var task = db.Tasks.FirstOrDefault(co => co.TaskId == pId);
                task.StartTime = pTask.StartTime;
                task.EndTime = pTask.EndTime;
                task.TaskDescription = pTask.TaskDescription;
                task.IsNew = false;
                base.SetObjectStatus(task);
                db.SaveChanges();

                return RedirectToAction<TaskController>(r => r.Index()).WithSuccess(string.Format("Task : '{0}' updated", pTask.TaskDescription));
            }
            catch
            {
                return View();
            }
        }


        // GET: Project/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Project/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [GridAction(EnableCustomBinding = true)]
        public virtual ActionResult ListTaskAjax(GridCommand command, SearchTaskModel search, Boolean IsFistLoad)
        {
            int TotalRecord = 0;
            int StartRecordIndex = (command.Page - 1) * command.PageSize;
            int EndRecordIndex = StartRecordIndex + command.PageSize;
            if (IsFistLoad)
                search.EndTime = DateTime.Now;
            var gridModel = new GridModel();
            var tasks = (from task in db.Tasks
                         join projects in db.Projects
                         on task.ProjectCode equals projects.ProjectCode
                         where ((DbFunctions.TruncateTime(task.StartTime) >= DbFunctions.TruncateTime(search.StartTime) && task.StartTime != null) || search.StartTime == null)
                         && ((DbFunctions.TruncateTime(task.StartTime) <= DbFunctions.TruncateTime(search.EndTime) && task.StartTime != null) || search.StartTime == null)
                         && (task.ProjectCode == search.ProjectCode || search.ProjectCode == null || search.ProjectCode == "")
                         select new TaskViewModel()
                         {
                             TaskId = task.TaskId,
                             TaskDescription = task.TaskDescription,
                             StartTime = task.StartTime,
                             EndTime = task.EndTime,
                             ProjectName = projects.ProjectName
                         }).ToList().OrderByDescending(or => or.StartTime);
            TotalRecord = tasks.ToList().Count();
            var GridTasks = tasks.ToList().Skip(StartRecordIndex).Take(EndRecordIndex);
            return View(new GridModel
            {
                Data = GridTasks,
                Total = TotalRecord
            });
        }

        //================================REPORT============================

        public ActionResult Report()
        {
            PrepareViewBag("", "");
            return View();
        }

        [GridAction(EnableCustomBinding = true)]
        public virtual ActionResult ReportTaskAjax(GridCommand command, SearchTaskModel search, Boolean IsFistLoad)
        {
            int TotalRecord = 0;
            int StartRecordIndex = (command.Page - 1) * command.PageSize;
            int EndRecordIndex = StartRecordIndex + command.PageSize;
            if (IsFistLoad)
                search.EndTime = DateTime.Now;
            var gridModel = new GridModel();
            var tasks = (from task in db.Tasks
                         join projects in db.Projects
                         on task.ProjectCode equals projects.ProjectCode
                         where ((DbFunctions.TruncateTime(task.StartTime) >= DbFunctions.TruncateTime(search.StartTime) && task.StartTime != null) || search.StartTime == null)
                         && ((DbFunctions.TruncateTime(task.StartTime) <= DbFunctions.TruncateTime(search.EndTime) && task.StartTime != null) || search.StartTime == null)
                         && (task.ProjectCode == search.ProjectCode || search.ProjectCode == null || search.ProjectCode == "")
                         select new TaskViewModel()
                         {
                             TaskId = task.TaskId,
                             TaskDescription = task.TaskDescription,
                             StartTime = task.StartTime,
                             EndTime = task.EndTime,
                             ProjectName = projects.ProjectName
                         }).ToList().OrderByDescending(or => or.StartTime);
            TotalRecord = tasks.ToList().Count();
            var GridTasks = tasks.ToList().Skip(StartRecordIndex).Take(EndRecordIndex);

            SessionUtility.SessionContainer.SetObject<List<TaskViewModel>>("TASKS", tasks.ToList());
            return View(new GridModel
            {
                Data = GridTasks,
                Total = TotalRecord
            });
        }

        public ActionResult UpdateSession(int TaskId, Boolean IsSelected)
        {
            var tasks = SessionUtility.SessionContainer.GetObject<List<TaskViewModel>>("TASKS");
            var task = tasks.FirstOrDefault(t => t.TaskId == TaskId).IsSelectedReport = IsSelected;

AmarSomoy/Views/Task/Create.cshtml
@using Telerik.Web.Mvc.UI

@model AmarSomoy.Models.TaskModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TaskModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.TaskId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TaskId, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.TaskId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CompanyCode, ViewBag.CompanyList as IEnumerable<SelectListItem>, "Select...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ProjectCode, ViewBag.ProjectList as IEnumerable<SelectListItem>, "Select...", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.TaskDescription, htmlAttributes: new { @class = "k-textbox", style = "width: 100%;height:80px" })
                @Html.ValidationMessageFor(model => model.TaskDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TaskOwnerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.TaskOwnerId)
                @Html.EditorFor(model => model.TaskOwner, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.TaskOwner, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="btnCreate" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            toastr.info('Page Loaded!');
            $('#btnCreate').click(function () {

                var datahModel = {
                    CompanyCode: $('#CompanyCode').val(),
                    ProjectCode: $('#ProjectCode').val(),
                    StartTime: $('#StartTime').val(),
                    EndTime: $('#EndTime').val(),
                    TaskDescription: $('#TaskDescription').val(),
                    TaskOwnerId: $('#TaskOwnerId').val(),
                    TaskOwner: $('#TaskOwner').val()

                };

                $.ajax({
                    url: "@Url.Action("Create", "Task")",
                    type: "POST",
                    data: datahModel,
                    dataType: "json",
                    success: function (data) {
                        console.log(data);
                        if (data.STATUS == "Success") {
                            toastr.success(data.MESSAGE, data.STATUS);
                            window.setTimeout(function () { window.location = "@Url.Action("Index", "Task")"; }, 2000)
                        }
                        else if (data.STATUS == "Validation")
                            toastr.warning(data.MESSAGE, data.STATUS);
                        else if (data.STATUS == "Exception")
                            toastr.error(data.MESSAGE, data.STATUS);
                    },
                    error: function (xhr, httpStatus, msg) {
                        toastr.error("Error! Please try again", "Error");
                    }
                });

                return false;
            });
        });
    </script>
}

AmarSomoy/Views/Task/Index.cshtml
@using Telerik.Web.Mvc.UI
@model AmarSomoy.Models.ViewModel.SearchTaskModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<fieldset>
    <legend>Search Tasks</legend>
    <table style="width:100%;">
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.ProjectCode, ViewBag.ProjectList as IEnumerable<SelectListItem>, "Select...", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.StartTime)
                    @Html.ValidationMessageFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.EndTime)
                    @Html.ValidationMessageFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <p>
                    <input type="submit" value="Search" id="btnSearch" />
                </p>
            </td>
        </tr>
    </table>
</fieldset>


@(Html.Telerik().Grid<AmarSomoy.Models.ViewModel.TaskViewModel>()
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(c => c.TaskDescription).ClientTemplate(
          Html.ActionLink("<#= TaskDescription #>", "Edit", "Task", new { pId = "<#= TaskId #>" }, null).ToString()

     );
        columns.Bound(c => c.StartTime);
        columns.Bound(c => c.EndTime);
        columns.Bound(c => c.WorkingHour);
        columns.Bound(c => c.ProjectName);

    }).DataBinding(d => d.Ajax().Select("ListTaskAjax", "Task", new { IsFistLoad = true }))
    .Pageable()
)

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {
            $('#btnSearch').click(function () {
                var grid = $('#Grid').data('tGrid');
                var searchModel = {
                    ProjectCode: $('#ProjectCode').val(),
                    StartTime: $('#StartTime').val(),
                    EndTime: $('#EndTime').val()
                    //Active: $('#Active').is(':checked')
                };
                grid.rebind({ search: searchModel, IsFistLoad: false });
                return false;
            });
        });
    </script>
}

AmarSomoy/Views/Task/MonthlyReport.cshtml
@using Telerik.Web.Mvc.UI
@model AmarSomoy.Models.ViewModel.SearchTaskModel

@{
    ViewBag.Title = "Weekly Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<fieldset>
    <legend>Search Tasks</legend>
    <table style="width:100%;">
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.ProjectCode, ViewBag.ProjectList as IEnumerable<SelectListItem>, "Select...", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.StartTime)
                    @Html.ValidationMessageFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.EndTime)
                    @Html.ValidationMessageFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <p>
                    <input type="submit" value="Search" id="btnSearch" />
                </p>

                <p>
                    <input type="submit" value="Report" id="btnReport" />
                </p>
            </td>
        </tr>
    </table>
</fieldset>


@(Html.Telerik().Grid<AmarSomoy.Models.ViewModel.TaskViewModel>()
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(c => c.TaskDescription).ClientTemplate(
        Html.ActionLink("<#= TaskDescription #>", "Edit", "Task", new { pId = "<#= TaskId #>" }, null).ToString()

   );
        columns.Bound(c => c.StartTime);
        columns.Bound(c => c.EndTime);
        columns.Bound(c => c.WorkingHour);
        columns.Bound(c => c.ProjectName);

    }).DataBinding(d => d.Ajax().Select("MonthlyReportTaskAjax", "Task", new { IsFistLoad = true }))
    .Pageable()
)

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#btnSearch').click(function () {
                var grid = $('#Grid').data('tGrid');
                var searchModel = {
                    ProjectCode: $('#ProjectCode').val(),
                    StartTime: $('#StartTime').val(),
                    EndTime: $('#EndTime').val()
                    //Active: $('#Active').is(':checked')
                };
                grid.rebind({ search: searchModel, IsFistLoad: false });
                return false;
            });

            $('#btnReport').click(function () {
                $.ajax({
                    url: "@Url.Action("SendReport", "Task")",
                    type: "POST",
                    data: {},
                    dataType: "json",
                    success: function (data) {
                    },
                    error: function (xhr, httpStatus, msg) {
                    }
                });

                return false;
            });

            @*$("#btnReport").click(function () {

                var dataObject = {
                    EmailAddressTo: $("#EmailAddressTo").val(),
                    NotifyEventsId: $("#NotifyEventsId").val(),
                    EnrollmentId: $("#ddlEnrollment").val(),
                    IsInternal: false,
                    FirstName: $("#FirstName").val(),
                    LastName: $("#LastName").val(),
                    EmailAddressCC: $("#EmailAddressCC").val()
                };
                $.ajax({
                    url: "@Url.Action("Create", "NotifyEmails")",
                    type: "POST",
                data: dataObject,
                dataType: "json",
                success: function (data) {
                    upass_custom_alert(data, "Success");
                },
                error: function (xhr, httpStatus, msg) {
                    upass_custom_alert("Error! Please try again", "Error");
                }
            });
        });*@

        });
        function checkboxClicked(checkBox) {
            var dataObject = {
                TaskId: checkBox.value,
                IsSelected: checkBox.checked
            };
            $.ajax({
                url: "@Url.Action("UpdateSession", "Task")",
                type: "POST",
                data: dataObject,
                dataType: "json",
                success: function (data) {
                    //upass_custom_alert(data, "Success");
                },
                error: function (xhr, httpStatus, msg) {
                    //upass_custom_alert("Error! Please try again", "Error");
                }
            });

        }

    </script>
}

AmarSomoy/Views/Task/Report.cshtml
@using Telerik.Web.Mvc.UI
@model AmarSomoy.Models.ViewModel.SearchTaskModel

@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<fieldset>
    <legend>Search Tasks</legend>
    <table style="width:100%;">
        <tr>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.ProjectCode, ViewBag.ProjectList as IEnumerable<SelectListItem>, "Select...", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ProjectCode)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.StartTime)
                    @Html.ValidationMessageFor(model => model.StartTime)
                </div>
            </td>
            <td>
                <div class="editor-label">
                    @Html.LabelFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <div class="editor-field">
                    @Html.EditorFor(model => model.EndTime)
                    @Html.ValidationMessageFor(model => model.EndTime)
                </div>
            </td>
            <td>
                <p>
                    <input type="submit" value="Search" id="btnSearch" />
                </p>

                <p>
                    <input type="submit" value="Report" id="btnReport" />
                </p>
            </td>
        </tr>
    </table>
</fieldset>


@(Html.Telerik().Grid<AmarSomoy.Models.ViewModel.TaskViewModel>()
    .Name("Grid")
    .Columns(columns =>
    {
        columns.Bound(o => o.TaskId)
                        .ClientTemplate("<input type='checkbox' id='chkMessage' name='checkedRecords' value='<#= TaskId #>' onclick='checkboxClicked(this)'/>")
                        .Title("Check")
                        .Width(50)
                        .HtmlAttributes(new { style = "text-align:center" });

        columns.Bound(c => c.TaskDescription).ClientTemplate(
          Html.ActionLink("<#= TaskDescription #>", "Edit", "Task", new { pId = "<#= TaskId #>" }, null).ToString()

     );
        columns.Bound(c => c.StartTime);
        columns.Bound(c => c.EndTime);
        columns.Bound(c => c.WorkingHour);
        columns.Bound(c => c.ProjectName);

    }).DataBinding(d => d.Ajax().Select("ReportTaskAjax", "Task", new { IsFistLoad = true }))
    .Pageable()
)

@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#btnSearch').click(function () {
                var grid = $('#Grid').data('tGrid');
                var searchModel = {
                    ProjectCode: $('#ProjectCode').val(),
                    StartTime: $('#StartTime').val(),
                    EndTime: $('#EndTime').val()
                    //Active: $('#Active').is(':checked')
                };
                grid.rebind({ search: searchModel, IsFistLoad: false });
                return false;
            });

            $('#btnReport').click(function () {
                //var grid = $('#Grid').data('tGrid');
                //var checks = $('#Grid').data('tGrid').columns[0];
                //$(checks).each(function (i, obj) {
                //    console.log($(obj).checked);
                //    //console.log(($(obj).is(':checked')));
                //});

                $.ajax({
                    url: "@Url.Action("SendReport", "Task")",
                    type: "POST",
                    data: {},
                dataType: "json",
                success: function (data) {
                    //upass_custom_alert(data, "Success");
                },
                error: function (xhr, httpStatus, msg) {
                    //upass_custom_alert("Error! Please try again", "Error");
                }
                });

                return false;
            });

            @*$("#btnReport").click(function () {

                var dataObject = {
                    EmailAddressTo: $("#EmailAddressTo").val(),
                    NotifyEventsId: $("#NotifyEventsId").val(),
                    EnrollmentId: $("#ddlEnrollment").val(),
                    IsInternal: false,
                    FirstName: $("#FirstName").val(),
                    LastName: $("#LastName").val(),
                    EmailAddressCC: $("#EmailAddressCC").val()
                };
                $.ajax({
                    url: "@Url.Action("Create", "NotifyEmails")",
                    type: "POST",
                data: dataObject,
                dataType: "json",
                success: function (data) {
                    upass_custom_alert(data, "Success");
                },
                error: function (xhr, httpStatus, msg) {
                    upass_custom_alert("Error! Please try again", "Error");
                }
            });
        });*@
            
        });
        function checkboxClicked(checkBox) {
            var dataObject = {
                TaskId: checkBox.value,
                IsSelected: checkBox.checked
            };
            $.ajax({
                url: "@Url.Action("UpdateSession", "Task")",
                type: "POST",
            data: dataObject,
            dataType: "json",
            success: function (data) {
                //upass_custom_alert(data, "Success");
            },
            error: function (xhr, httpStatus, msg) {
                //upass_custom_alert("Error! Please try again", "Error");
            }
            });

        }

    </script>
}